
samples:
  sample1: "sample_data/raw_reads/sample1.fastq.gz"
  sample2: "sample_data/raw_reads/sample2.fastq.gz"
  sample3: "sample_data/raw_reads/sample3.fastq.gz"

genome: sample_data/amplicon.fa

adapters: sample_data/adapters/TruSeq2-SE.fa

nodeN: 4
