---
title: "Timecourse"
output:
  html_notebook:
    toc:        TRUE
    toc_float:  TRUE
    theme:      "lumen"
    number_sections: FALSE
    code_folding: "hide"
    self_contained: TRUE
date: "r Sys.Date()"
---

```{r, child="_settings.Rmd"}
#Read config.yml for the locations of sample sheet, pipeline output and sigmut loc and variants_dir
```

```{r libraries and input,echo=F}
df_var <- read.table(var_timecourse_csv, sep = "\t", header=T)
df_mut <- read.table(mut_timecourse_csv, sep = "\t", header=T)
```

# VARIANTS

## Show Variants (all timepoints)

When you click on the legend the trace are set ON/ OFF. 

```{r bubble plot,echo=F}
forplot<- reshape2::melt(df_var,id.vars=c("dates","samplename","time","location_name","coordinates_lat","coordinates_long","WT","b1351","b117"))
forplot$dates <- as.Date(forplot$dates)

bubble<-plot_ly (
  data= forplot,
  type = 'scattergeo',
  mode='markers')

bubble <- bubble %>% add_trace(
  lon =forplot$coordinates_long ,
  lat =forplot$coordinates_lat,
  marker = list (
  color =rep("red",10) ,
  size = forplot$WT*100,
  mode = 'markers'),
  name= "WT",
  visible=TRUE
  ) %>%

add_trace(
  lon =forplot$coordinates_long ,
  lat =forplot$coordinates_lat,
  marker = list (
  color =rep("blue",10) ,
  size = forplot$b1351*100,
  mode = 'markers'),
  name= "b1351",
  visible=TRUE
  ) %>% 
  
add_trace(
  lon =forplot$coordinates_long ,
  lat =forplot$coordinates_lat,
  marker = list (
  color =rep("green",10) ,
  size = forplot$b117*100,
  mode = 'markers'),
  name= "b117",
  visible=TRUE
  )


bubble
```

## variants over time for each location 
```{r variants, echo=F}
#from rafael
forplot<- reshape2::melt(df_var,id.vars=c("dates","samplename","time","location_name","coordinates_lat","coordinates_long"))
forplot$dates <- as.Date(forplot$dates)
locations <- unique(forplot$location_name)
plots_line_locations <- lapply(locations, function(location) {
  tmp <- forplot  %>% filter(location_name ==location) 
  fig <- plot_ly(x = tmp$dates,name=tmp$variable,y = tmp$value, type = 'scatter',mode = 'lines') %>%    
  layout(title = location)
  fig <- fig %>% add_markers(marker = list(line = list(color = "black", width = 1)))
})
```


```{r plot variants over time, echo=F}
#plots_line_locations
plots_line_locations[[1]]
plots_line_locations[[2]]
plots_line_locations[[3]]
plots_line_locations[[4]]
plots_line_locations[[5]]
plots_line_locations[[6]]
```



## variants on the map for each date/location

```{r maps for variants, echo=F}
forplot<- reshape2::melt(df_var,id.vars=c("dates","samplename","time","location_name","coordinates_lat","coordinates_long"))
forplot$dates <- as.Date(forplot$dates)
locations <- unique(forplot$location_name)

dates <- unique(forplot$dates)
#variants <- unique(forplot$variable)
plots_maps<- lapply(dates, function(date) {
    tmp <- forplot  %>% filter(dates ==date) 
    tmp$text <- as.character(tmp$value)
    if (all(is.na(tmp$coordinates_long))== FALSE )  {
          tmp[is.na(tmp)] <- 0
          bubble<-plot_ly (
          data= tmp,
          type = 'scattermapbox',
          mode='markers',
          size = ~value,
          lon =~coordinates_long,
          lat =~coordinates_lat,
          name=~variable,
          color=~variable,
          text = ~text,
          fill = ~'',
          marker = list(sizemode = 'diameter'),
          hovertemplate = "Freq: %{text}"
          ) %>% 
          layout(title=paste0(date),mapbox = list(zoom = 5.5,
                                                              center = list(lat =min(tmp$coordinates_lat,na.rm=TRUE), 
                                                                            lon =min(tmp$coordinates_long,na.rm=TRUE)),
                                                              style = 'open-street-map'))
    }
  })
plots_maps[[1]]
plots_maps[[2]]
plots_maps[[3]]
plots_maps[[4]]
plots_maps[[5]]
plots_maps[[6]]
plots_maps[[7]]
plots_maps[[8]]
```


# MUTATIONS

## mutations  over time for each location 
```{r mutations, echo=F}
forplot<- reshape2::melt(df_mut,id.vars=c("dates","samplename","time","location_name","coordinates_lat","coordinates_long"))
forplot$dates <- as.Date(forplot$dates)
locations <- unique(forplot$location_name)
plots_line_locations <- lapply(locations, function(location) {
  tmp <- forplot  %>% filter(location_name ==location) 
  fig <- plot_ly(x = tmp$dates,name=tmp$variable,y = tmp$value, type = 'scatter',mode = 'lines') %>%    
  layout(title = location)
  fig <- fig %>% add_markers(marker = list(line = list(color = "black", width = 1)))
})
```


```{r plot mutations over time, echo=F}
plots_line_locations[[1]]
plots_line_locations[[2]]
plots_line_locations[[3]]
plots_line_locations[[4]]
plots_line_locations[[5]]
plots_line_locations[[6]]
```

## mutations on the map for each data/location

```{r mutations for locations and date, echo=F}
forplot<- reshape2::melt(df_mut,id.vars=c("dates","samplename","time","location_name","coordinates_lat","coordinates_long"))
forplot$dates <- as.Date(forplot$dates)
locations <- unique(forplot$location_name)

dates <- unique(forplot$dates)
#variants <- unique(forplot$variable)
plots_maps<- lapply(dates, function(date) {
    tmp <- forplot  %>% filter(dates ==date) 
    tmp$text <- as.character(tmp$value)
    if (all(is.na(tmp$coordinates_long))== FALSE )  {
          tmp[is.na(tmp)] <- 0
          bubble<-plot_ly (
          data= tmp,
          type = 'scattermapbox',
          mode='markers',
          size = ~value,
          lon =~coordinates_long,
          lat =~coordinates_lat,
          name=~variable,
          color=~variable,
          text = ~text,
          fill = ~'',
          marker = list(sizemode = 'diameter'),
          hovertemplate = "Freq: %{text}"
          ) %>% 
          layout(title=paste0(date),mapbox = list(zoom = 5.5,
                                                              center = list(lat =min(tmp$coordinates_lat,na.rm=TRUE), 
                                                                            lon =min(tmp$coordinates_long,na.rm=TRUE)),
                                                              style = 'open-street-map'))
    }
  })
plots_maps[[1]]
plots_maps[[2]]
plots_maps[[3]]
plots_maps[[4]]
plots_maps[[5]]
plots_maps[[6]]
plots_maps[[7]]
plots_maps[[8]]
```




```{r bubble mutations plot,echo=F,eval=F}
#does not work in a loop
forplot<- reshape2::melt(df_mut,id.vars=colnames(df_mut))
forplot$dates <- as.Date(forplot$dates)

b<-plot_ly (
  data= forplot,
  type = 'scattergeo',
  mode='markers')

mutations <- colnames(df_mut)[7:length(colnames(df_mut))]
for (mut in mutations){
  print(mut)
  b <- b %>% add_trace(
    lon =forplot$coordinates_long ,
    lat =forplot$coordinates_lat,
    marker = list(size = forplot[[as.name(mut)]]*100, mode = 'markers',color=rep("red",length(rownames(df_mut)))),
    name = mut,
    visible = F)
}

b <- b %>% layout(title = "Varints")


b
```

