---
title: "Table of Links to Reports"
date: '`r format(as.POSIXct(if ("" != Sys.getenv("SOURCE_DATE_EPOCH")) { as.numeric(Sys.getenv("SOURCE_DATE_EPOCH")) } else { Sys.time() }, origin="1970-01-01"), "%Y-%m-%d %H:%M:%S")`'
params:
  sample_sheet: ''
---






For each sample that was provided three report pages were generated. These can be found here by clicking on the provided link or by navigating through the tabs of this website.

```{r libs, echo=F, warning=F, message=F}
library(data.table)
library(DT)
```


```{r read sample file, echo=F}

sample_sheet <- fread(params$sample_sheet)
sample_names <- sample_sheet$name
report_name <- c("variant_report", "qc_report","taxonomic_classification")
report_link <- c(".variantreport_p_sample.html",".qc_report_per_sample.html",".taxonomic_classification.html")

```


```{r table with links, echo=FALSE}
df <- as.data.frame(dplyr::select(sample_sheet,location_name, date, name))

#todo: make links correct
#loop over the three reports and each sample and create the link
for (i in (1:length(report_name))){
  #print(i)
  colname<- report_name[i]
  col <- c()
  for (sample in sample_names){
    #print(sample)
    link <- paste0("<a href=",sample,report_link[i],">",report_name[i],"</a>")
    col <- c(col,link)
  }
  df[[colname]] <-col
}


#reshape into long format
df <- reshape2::melt(df, id.vars= c("location_name","date","name"), value.name = "link")
df <- df[,-5]
```

```{r plot table}
DT::datatable(df,filter = "bottom",escape=F)

```
