# ------------------------------------------------------------ #
genome:
    name: 'mm9'
    fasta: '/data/akalin/vfranke/AAkalin_PIX/ChIP/Genome/chr19.fa'
index: 

fastq: '/data/akalin/vfranke/AAkalin_PIX/ChIP/Fastq'


samples:
    ChIP1: 
        fastq: 
            - ChIP.fq.gz
        library: single
    Cont1:
        fastq: 
            - Cont.fq.gz
        library: single
    ChIP2:
        fastq: 
            - ChIP.fq
        library: single
    Cont2:
        fastq: 
            - Cont.fq
        library: single
    ChIPpe:
        fastq: 
            - ChIP_1.fq.gz
            - ChIP_2.fq.gz
        library: paired
        
# ------------------------------------------------------------ #
# ChIP and Cont are hardcoded and must exist in the config file
peak_calling:
    Peaks1:
        ChIP: ChIP1
        Cont: Cont1
        params:
            macs2:
                nomodel: ''
                extsize: 300
    Peaks2:
        ChIP: ChIP2
        Cont: Cont2
        params:
            macs2:
                nomodel: ''
                extsize: 147
    Peaks3:
        ChIP: ChIPpe
        Cont: Cont2
        params:
            macs2:
                nomodel: ''
                
    Peaks4:
        ChIP: 
            - ChIP1
            - ChIP2
        Cont: 
            - Cont1
            - Cont2        
        params:
            macs2:
                nomodel: ''
                

# ------------------------------------------------------------ #
idr:
    ChIP_IDR:
        ChIP1: Peaks1
        ChIP2: Peaks2

# ------------------------------------------------------------ #
params:
    extend: 200
    bowtie2:
        k: 1
    idr:
        idr-threshold: 0.1
    macs2:
        g: hs
        keep-dup: auto
        q: 0.05





# unspecified dependencies:
# sytem ln
