# ------------------------------------------------------------ #
genome:
    name: 'mm9'
    fasta: '/data/akalin/vfranke/AAkalin_PIX/ChIP/Genome/chr19.fa'
index:

annotation:
    gtf: "/data/akalin/Base/Annotation/mm9/EnsemblGenes/150520_Ensembl_Mus_musculus.NCBIM37.67.form.gtf"
    cpg_island: '/data/akalin/Base/Annotation/mm9/CpGi/mm9.cpg.islands.bed'

fastq: '/data/akalin/vfranke/AAkalin_PIX/ChIP/Fastq'

# ------------------------------------------------------------ #
# mapping
samples:
    ChIP1:
        fastq:
            - ChIP.fq.gz
        library: single
    Cont1:
        fastq:
            - Cont.fq.gz
        library: single
    ChIP2:
        fastq:
            - ChIP.fq
        library: single
    Cont2:
        fastq:
            - Cont.fq
        library: single
    ChIPpe:
        fastq:
            - ChIP_1.fq.gz
            - ChIP_2.fq.gz
        library: paired

# ------------------------------------------------------------ #
# ChIP and Cont are hardcoded and must exist in the config file
peak_calling:
    Peaks1:
        ChIP: ChIP1
        Cont: Cont1
        params:
            macs2:
                nomodel: ''
                extsize: 300
    Peaks2:
        ChIP: ChIP2
        Cont: Cont2
        params:
            macs2:
                nomodel: ''
                extsize: 147
    Peaks3:
        ChIP: ChIPpe
        Cont: Cont2
        params:
            macs2:
                nomodel: ''

    Peaks4:
        ChIP:
            - ChIP1
            - ChIP2
        Cont:
            - Cont1
            - Cont2
        params:
            macs2:
                nomodel: ''

    Peaks5:
        ChIP: ChIP2
        Cont:
            - Cont1
            - Cont2
        params:
            macs2:
                nomodel: ''

    Peaks6:
        ChIP: ChIP1
        Cont:
        params:
            macs2:
                nomodel: ''
    Peaks7:
        ChIP: ChIP1
        Cont:
        params:
            macs2:
                broad: ''

# ------------------------------------------------------------ #
idr:
    ChIP_IDR:
        ChIP1: Peaks1
        ChIP2: Peaks2

# ------------------------------------------------------------ #
hub:
    name: Pix_Hub
    shortLabel: Pix_Short
    longLabel: Pix_Hub_Long
    email: vedran.franke@mdc-berlin.de
    descriptionUrl: hub.html
    super_tracks:
        Tracks1:
            track11:
                name: Peaks1
                type: macs
            track12:
                name: ChIP1
                type: bigWig
            long_label: Tracks1_long
        Tracks2:
            track21:
                name: Peaks2
                type: macs
            track22:
                name: ChIP2
                type: bigWig
            track23:
                name: Peaks3
                type: macs
            track24:
                name: ChIPpe
                type: bigWig
# ------------------------------------------------------------ #
feature_combination:
    idr:
        - ChIP_IDR
    peaks:
        - Peaks6
        - Peaks5



params:
    extend: 200
    scale_bw: 'yes'
    bowtie2:
        k: 1
    idr:
        idr-threshold: 0.1
    macs2:
        g: hs
        keep-dup: auto
        q: 0.05





# unspecified dependencies:
# sytem ln
