# ------------------------------------------------------------ #
annotation:
    primary:
        genome:
            name: 'hg19'
            fasta: '/data/local/vfranke/AAkalin_PIX/scRNA/Base/hg19.chr19.fa'
        gtf: '/data/local/vfranke/AAkalin_PIX/scRNA/Base/hg19.chr19.gtf'
     
    secondary:
        genome:
            name: 'mm9'
            fasta: '/data/local/vfranke/AAkalin_PIX/scRNA/Base/mm9.chr19.fa'
        gtf: '/data/local/vfranke/AAkalin_PIX/scRNA/Base/mm9.chr19.gtf'
    

fastq: '/data/local/vfranke/AAkalin_PIX/scRNA/001-42802245'


samples:
    Sample1:
        barcode: HUMANMOUSE1_S1_L001_R1_001.fastq.gz
        reads: HUMANMOUSE1_S1_L001_R2_001.fastq.gz
        method: dropseq

    Sample2:
        barcode: HUMANMOUSE1_S1_L001_R1_001.fastq.gz
        reads: HUMANMOUSE1_S1_L001_R2_001.fastq.gz
        method: dropseq
            
        

# ------------------------------------------------------------ #
params:
    genes_per_cell: 10
    num_core_barcodes: 10


