locations:
  reads-folder: /data/local/buyar/test_pigx_pipelines/rnaseq/example_data/reads/
  output-folder: /data/local/buyar/test_pigx_pipelines/rnaseq/example_output/
  genome-fasta: /data/local/buyar/test_pigx_pipelines/rnaseq/example_data/fasta/chr22.fa
  gtf-file: /data/local/buyar/test_pigx_pipelines/rnaseq/example_data/gff/hg38/ensembl82_and_ercc.chr22.gtf
tools:
  fastqc:
    executable: fastqc
  multiqc:
    executable: multiqc
  star:
    executable: STAR
    n-threads: 8
  trim-galore:
    executable: trim_galore
    args: "--paired"
  bamCoverage:
    executable: bamCoverage
  samtools:
    executable: samtools
  htseq-count:
    executable: htseq-count
  R:
    Rscript: Rscript 
    executable: R
