locations:
  input-dir: '/data/akalin/vfranke/AAkalin_PIX/ChIP/Fastq'
  output-dir: '/home/vfranke/Tmp/pigxtest'
  genome-file: '/data/akalin/vfranke/AAkalin_PIX/ChIP/Genome/chr19.fa'
  index-dir:
  annotation:
      gff-file: "/data/akalin/Base/Annotation/mm9/EnsemblGenes/150520_Ensembl_Mus_musculus.NCBIM37.67.form.gtf"


general:
  assembly: hg19
  params:
    extend: 200
    scale_bw: 'yes'
    bowtie2:
        k: 1
    idr:
        idr-threshold: 0.1
    macs2:
        g: hs
        keep-dup: auto
        q: 0.05
    extract_signal:
        expand_peak: 200
        bin_num: 20
