locations:
  reads-folder: /data/akalin/Projects/pigx_rnaseq/example_data
  output-folder: /data/akalin/Projects/pigx_rnaseq/example_output
  genome-folder: /data/akalin/Base/GenomeIndices/hg38/STAR/EnsemblGenes_ERCC_sjdb99/
  gtf-file: /data/akalin/Base/GenomeIndices/hg38/STAR/EnsemblGenes_ERCC_sjdb99/ensembl82_and_ercc.gtf
tools:
  fastqc:
    executable: /home/jronen/bin/fastqc
  multiqc:
    executable: /home/jronen/beast-centos7-home/miniconda/envs/conda361/bin/multiqc
  star:
    executable: /home/jronen/.guix-profile/bin/STAR
    n-threads: 2
  trim-galore:
    executable: /home/jronen/bin/trim_galore
    args: "--paired"
  bamCoverage:
    executable: /home/jronen/beast-centos7-home/miniconda/envs/conda361/bin/bamCoverage
  samtools:
    executable: samtools
  featureCounts:
    executable: featureCounts