locations:
  reads-folder: /data/akalin/Projects/Rajewsky_Sommermann_ExomeSeq/Data/Raw
  output-folder: /scratch/AG_Akalin/jona/temp/tom/
  genome-folder: /data/akalin/Base/GenomeIndices/hg38/STAR/EnsemblGenes_ERCC_sjdb99/
tools:
  fastqc:
    executable: /homr/jronen/bin/fastqc
  multiqc:
    executable: /home/jronen/.virtualenvs/bio352/bin/multiqc
  star:
    executable: /home/jronen/.guix-profile/bin/STAR
    n-threads: 2
  trim-galore:
    executable: /home/jronen//bin/trim_galore
    args: "--paired"
