import os, csv
from SRA2fastq_functions import *

# An example to test it
# config = {"ftp_sra":{'SRR2075691': 'ftp.sra.ebi.ac.uk/vol1/fastq/SRR207/001/SRR2075691/SRR2075691.fastq.gz', 'SRR1042451_1': 'ftp.sra.ebi.ac.uk/vol1/fastq/SRR104/001/SRR1042451/SRR1042451_1.fastq.gz', 'SRR2075687': 'ftp.sra.ebi.ac.uk/vol1/fastq/SRR207/007/SRR2075687/SRR2075687.fastq.gz', 'SRR2075689': 'ftp.sra.ebi.ac.uk/vol1/fastq/SRR207/009/SRR2075689/SRR2075689.fastq.gz'}, 'in'="~/mydirectory/"}

SAMPLES_DICT = config["ftp_sra"]
MYDIR = config['in']

        
# Get fastq files from the ENA database.
rule download: 
     output: 
         MYDIR + "{run_id}.fastq.gz" 
     run: 
          #wget_file(MYDIR + wildcards.run_id+".fastq.gz",
          #            SAMPLES_DICT[wildcards.run_id])
          os.system("touch "+ MYDIR + wildcards.run_id+".fastq.gz")

                
                
