genome:
    name: 'mm9'
    fasta: '/data/akalin/Base/Genomes/mm9/mm9.fa'
index: 

fastq: '/data/akalin/vfranke/AAkalin_PIX/ChIP/Fastq'


samples:
    ChIP1: 
        fastq: ChIP.fq
        library: single
    Cont1:
        fastq: Cont.fq
        library: single
    ChIP2:
        fastq: ChIP.fq
        library: single
    Cont2:
        fastq: Cont.fq
        library: single

peak_calling:
    Peaks1:
        ChIP: ChIP1
        Cont: Cont1
    Peaks2:
        ChIP: ChIP2
        Cont: Cont2

idr:
    ChIP_IDR:
        ChIP1: Peaks1
        ChIP2: Peaks2

params:
    extend: 200
    bowtie2:
        k: 1
    idr:
        idr-threshold: 0.1
    macs2:
        g: hs
        keep-dup: auto
        q: 0.05





# unspecified dependencies:
# sytem ln
