genome:
    name: 'mm9'
    fasta:
index: '/data/local/vfranke/AAkalin_PIX/ChIP/Bowtie_Index/'

fastq: '/data/local/vfranke/AAkalin_PIX/ChIP/Fastq'


samples:
    ChIP1: ChIP.fq
    Cont1: Cont.fq
    ChIP2: ChIP.fq
    Cont2: Cont.fq

peak_calling:
    Peaks1:
        ChIP: ChIP1
        Cont: Cont1
    Peaks2:
        ChIP: ChIP2
        Cont: Cont2

idr:
    ChIP_IDR:
        ChIP1: Peaks1
        ChIP2: Peaks2

params:
    extend: 200
    bowtie:
        k: 1
        m: 1
        best: ''
        strata: ''
    idr:
        idr-threshold: 0.1
    macs2:
        g: hs
        keep-dup: auto
        B: False
        SPMR: False
        q: 0.05


software:
    fastqc: fastqc
    bamToBed: bamToBed
    bowtie: bowtie
    bowtie-build: bowtie-build
    genomeCoverageBed: genomeCoverageBed
    idr: idr
    macs2: macs2
    perl: perl
    R: R # data.table dependency
    samtools: samtools
    wigToBigWig: wigToBigWig


# unspecified dependencies:
# sytem ln
